// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR7ZNAE83SMjgW83gtNjOkvvjpPFgdOUE',
    appId: '1:469007730974:web:48020ca26087089e6ce10f',
    messagingSenderId: '469007730974',
    projectId: 'notes-management-app-ostad',
    authDomain: 'notes-management-app-ostad.firebaseapp.com',
    storageBucket: 'notes-management-app-ostad.firebasestorage.app',
    measurementId: 'G-2GPX6SH5B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRsEEpEULNgJqwhhNi8ukMrAJltPxD5x4',
    appId: '1:469007730974:android:23082127ef679cb76ce10f',
    messagingSenderId: '469007730974',
    projectId: 'notes-management-app-ostad',
    storageBucket: 'notes-management-app-ostad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArVtAqqv1zABrOiAwYTTeLG6t4ryl0Zgc',
    appId: '1:469007730974:ios:9662534e8892fa946ce10f',
    messagingSenderId: '469007730974',
    projectId: 'notes-management-app-ostad',
    storageBucket: 'notes-management-app-ostad.firebasestorage.app',
    iosBundleId: 'com.ostad.notes.notesManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR7ZNAE83SMjgW83gtNjOkvvjpPFgdOUE',
    appId: '1:469007730974:web:9d2e7cfa21cc9a0b6ce10f',
    messagingSenderId: '469007730974',
    projectId: 'notes-management-app-ostad',
    authDomain: 'notes-management-app-ostad.firebaseapp.com',
    storageBucket: 'notes-management-app-ostad.firebasestorage.app',
    measurementId: 'G-NEP0PQ7LMZ',
  );
}
